function [sensors, sensorQuant, attachment] = createMySensors(scenario)

profiles = actorProfiles(scenario);
poses = actorPoses(scenario);
sensors{1} = radarDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [0 0], ...
    'MaxRange', 15, ...
    'FieldOfView', [180 5], ...
    'Yaw', 0, ...
    'ActorProfiles', profiles,...
    'UpdateInterval', 0.02);

sensors{2} = visionDetectionGenerator('SensorIndex', 2, ...
    'SensorLocation', [0 0], ...
    'MaxRange', 30, ...
    'DetectorOutput', 'Objects only', ...
    'Yaw', 0, ...
    'ActorProfiles', profiles,...
    'UpdateInterval', 0.02);

sensors{3} = radarDetectionGenerator('SensorIndex', 3, ...
    'SensorLocation', [0 0], ...
    'MaxRange', 15, ...
    'FieldOfView', [180 5], ...
    'Yaw', 0, ...
    'ActorProfiles', profiles,...
    'UpdateInterval', 0.02);

sensors{4} = visionDetectionGenerator('SensorIndex', 4, ...
    'SensorLocation', [0 0], ...
    'MaxRange', 30, ...
    'DetectorOutput', 'Objects only', ...
    'Yaw', 0, ...
    'ActorProfiles', profiles,...
    'UpdateInterval', 0.02);


attachment = [1;1;2;2];
% Ändrat sensorer och var de ska sitta

sensorQuant = numel(sensors);
end